### ISSUE TITLE
Change directory structure(?)

### ISSUE THREAD

**Issue by SevereOverfl0w** [snoe/nvim-parinfer.js#1]
Should the directory structure be changed, to accommodate for plugin managers?

https://github.com/junegunn/vim-plug/issues/125 it's somewhat suggested here that you should provide your own rplugin/node directory, this will also alleviate worries of naming with the .js a little.

e.g. how floobits does it: https://github.com/Floobits/floobits-neovim

**Comment by snoe** [comment]
Thanks! I was just thinking about doing this.
