### ISSUE TITLE
Parinfer Mode Not Displayed In Airline After Commit in #9

### ISSUE THREAD

**Issue by ode79** [snoe/nvim-parinfer.js#10]
The fix you made in 3591df75160a270c3431b50a8de09f5a6157185d stops the Parinfer mode showing in the Airline.

**Comment by snoe** [comment]
Hrm seems to be working fine here, do you have `g:parinfer_airline_integration` set ?

**Comment by ode79** [comment]
No, I don't have `g:parinfer_airline_integration` set.

There is definitely a problem with the fix as when I clone nvim-parinfer.js into my bundle directory and open a Clojure file I have `Normal >` on the left of the airline.

When I checkout the previous commit (before the fix) I have `Normal indent >` and `indent` will change to `paren` etc if I change the mode.

**Comment by snoe** [comment]
So the previous commit was ignoring `g:loaded_airline` if `g:parinfer_airline_integration` was not set. I'm surprised that it was working previously but I think it's necessary to keep checking as it would cause a regression in #9.

I tested locally and I think what's happening is that you have the `Bundle 'nvim-parinfer.js'` bundle line above the airline bundle in your rc file. Is that the case? 

If not could you run `:echo &filetype exists('g:loaded_airline') g:loaded_airline exists('g:parinfer_airline_integration') g:parinfer_airline_integration` I'd expect to see: `clojure 1 1 0
E121: Undefined variable: g:parinfer_airline_integration
E15: Invalid expression: g:parinfer_airline_integration
Press ENTER or type command to continue`

**Comment by SevereOverfl0w** [comment]
There have been some airline changes lately, could they be related?

**Comment by ode79** [comment]
I'm not using bundle, I just clone git directories into the bundle directory manually and don't update unless I have a specific need.

The output I get is from the command you posted is:
```clojure 1 1 0```
```E121: Undefined variable: g:parinfer_airline_integration```
```E15: Invalid expression: g:parinfer_airline_integration```

I then set `let g:parinfer_airline_integration = 1` in init.vim and then I get:
```clojure 1 1 1 1```
But the paren mode still doesn't show in the airline.

**Comment by snoe** [comment]
I took another approach to #9, hopefully this solves your problem.

**Comment by ode79** [comment]
That fixed it, thanks.
