### ISSUE TITLE
Default to paren mode for bufenter indent

### ISSUE THREAD

**Issue by SevereOverfl0w** [snoe/nvim-parinfer.js#11]
Would it be possible to have the [bufenter](https://github.com/snoe/nvim-parinfer.js/blob/master/plugin/parinfer.vim#L19) command automatically run with paren mode? Using indent mode breaks incorrectly indented files.

If possible, it would be nice to be able to change the default _before_ this is executed.

**Comment by shaunlebron** [comment]
:+1: thanks guys.  this is definitely imperative
