### ISSUE TITLE
FYI - Parinfer now available in Vimscript

### ISSUE THREAD

**Issue by oakmac** [snoe/nvim-parinfer.js#12]
The core Parinfer algorithm is now available as a Vimscript library: https://github.com/oakmac/parinfer-viml

**Comment by snoe** [comment]
Thanks @oakmac. Part of the reason for this project is to show how neovim has enabled us to write tools for clojure(script) in clojurescript. Personally, I find this to a very powerful idea so this project will remain as a remote plugin.

If people are interested in a native vimscript version, it looks like https://github.com/bhurlow/vim-parinfer/issues/15 is heading down that path.

**Comment by oakmac** [comment]
:+1:
