### ISSUE TITLE
Are all lisps supported?

### ISSUE THREAD

**Issue by Superpat** [snoe/nvim-parinfer.js#16]
Is this supposed to work with all lisps or only clojure? I'm using guile and it doesnt seem to be working. 

I installed both node-host and parinfer through vim-plug, ran npm install inside node-host and used UpdateRemotePlugins inside neovim. But when I open a .scm file in neovim there doesnt seem to be anything going on.

Possible failure point:
Vim-Plug says the git clone returns an error on the first install, but after reinstall it succeeds.

**Comment by snoe** [comment]
So it's currently set to only run under the clojure file type see: https://github.com/snoe/nvim-parinfer.js/blob/master/plugin/parinfer.vim This is just uncovering my unfamiliarity with other lisps, afaik parinfer should work well with any sexpressions.

Iimmedoayly, after cloning you can either modify the filetypes there or mark guile extensions as clojure. 

I'm open to PRs or other direction to expanding default support.

**Comment by snoe** [comment]
The latest commit will enable parinfer for racket, lisp, and scheme filetypes. Let me know if you run into any problems with it here (we also hangout in #parinfer in clojurians slack channel).

**Comment by Superpat** [comment]
Thanks I'll test it out!
