### ISSUE TITLE
Error When Running with Node 5

### ISSUE THREAD

**Issue by ode79** [snoe/nvim-parinfer.js#17]
The below error occurs all the time (making the extension unusable) when running with Node 5.9.1 (Installed with a deb from Nodesource [specifically this package '5.9.1-1nodesource1~trusty1']):

```
Error detected while processing function <SNR>17_indent[6]..ParinferIndent:
line    1:
Invalid channel "2"
Press ENTER or type command to continue
```

Downgrading to v4 has fixed the problem.

I can't say if this is a new problem with v5 as I was on 0.12 before and needed to upgrade for something other than nvim-parinfer.js so this is the first and only time I have run with v5.

**Comment by snoe** [comment]
5.8.0 seems ok, but 5.9.0 also exhibits the problem. 

However, the [changelog](https://github.com/nodejs/node/blob/master/CHANGELOG.md#2016-03-16-version-590-stable-evanlucas) doesn't obviously have a breaking change. 

Sadly, I suspect this is going to be similar to https://github.com/neovim/node-host/issues/10 and might take awhile to figure out and fix. I'll keep this updated.

**Comment by ode79** [comment]
This issue must have been caused by a bug in a dependency for node-host as it can be fixed by `$ rm -rf node_modules/` in `nvim/bundle/node-host/` directory and then `npm install` in the same dir.

I've also tested on node 6 since it is out now and nvim-parinfer.js is also working fine there too.

**Comment by snoe** [comment]
Thanks for following up @ode79
