### ISSUE TITLE
E117: Unknown function: ParinferShift

### ISSUE THREAD

**Issue by ode79** [snoe/nvim-parinfer.js#18]
When trying to de-indent a form with `shift + <` I get the below error:

```
Error detected while processing function <SNR>17_parinferShiftCmd:
line   11:
E117: Unknown function: ParinferShift
```

**Comment by snoe** [comment]
Hi ode79, that error would pop up if you haven't run `:UpdateRemotePlugins` after updating.

**Comment by ode79** [comment]
You're right, I forgot to do this, and the error went away after I run the command.

Thanks
