### ISSUE TITLE
Recent Change in Neovim Causes Errors with nvim-parinfer.js

### ISSUE THREAD

**Issue by ode79** [snoe/nvim-parinfer.js#21]
I install Neovim from the Ubuntu PPA.

I wasn't updating daily but the last version of Neovim I have that worked with nvim-parinfer.js correctly is 
`vim_0.1.2ubuntu1+git201605270822+2539+19~ubuntu14.04.1_amd64.deb`.

I updated to `vim_0.1.4ubuntu1+git201606071432+2575+20~ubuntu14.04.1_amd64.deb` and now I get an error on startup (it goes away too quickly to read), and the below error every time there is a change in the file and the plugin runs.

```
Error dectected while processing function <SNR>17_indent[6]..ParinferIndent:
line	1:
Invalid channel "2"
````

I have updated to the daily Neovim from the PPA today and the errors still appear.

When I install the last working version nvim-parinfer.js runs without issue again.

**Comment by snoe** [comment]
Should be fixed by: https://github.com/neovim/node-host/pull/14 (easy to patch yourself by changing your `bundle/node-host/package.json` and running `npm install --production` if you don't want to wait for the repo)

**Comment by snoe** [comment]
@ode79 @zakak ^

**Comment by zakak** [comment]
Thank you for the fix (and the plugin), works for me on `0.1.4ubuntu1+git201606211627+2606+
20~ubuntu16.04.1`.

**Comment by snoe** [comment]
This has been fixed in node-host - you should be able to update the node-host plugin in your bundle now.

**Comment by burningTyger** [comment]
Same error with `1.1.0`. Had to change to `2.1.0` to make it work again.
