### ISSUE TITLE
Plugin doesn't load

### ISSUE THREAD

**Issue by SevereOverfl0w** [snoe/nvim-parinfer.js#7]
https://github.com/snoe/nvim-parinfer.js/commit/14463f605c00f366091d217dfce00db4579a8417

Plug no longer loads as of this commit, causes neovim to completely hang up!

Seeing this on your end? (intentional in-dev thing..ish?)

**Comment by SevereOverfl0w** [comment]
On ab1f02c1df164cc57c61b269f4ef0b84e03170d9 I see the following in my message buffer: 

`Error detected while processing function ParinferIndent:                                                                                                                                                                                       
line    1:                                                                                                                                                                                                                                     
E121: Undefined variable: g:parinfer_mode   `

**Comment by SevereOverfl0w** [comment]
https://github.com/neovim/node-host/commit/ce637f58d72f04c1ac274bdbc8aaa46c8994f59f 

^^ this commit seems to be the real culprit! burn it!

But in reality, is this an issue of us (incorrect api hacking?) or them (regression!)?

**Comment by snoe** [comment]
Yeah, that's our issue, I hadn't realized that node-host commit was released yet. There might be a semver problem but the plugin needs to be updated to work with the new api.

**Comment by SevereOverfl0w** [comment]
Ah! Hopefully a simple transition.

**Comment by snoe** [comment]
This should be fixed now. Make sure you have the latest node-host and npm deps.
